galaxy_info:
  author: J. Harte (@boonware)
  description: Migrate an AI Service instance when upgrading to a release that requires migration steps.
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - devops
    - migration

dependencies:
  - role: ibm.mas_devops.ansible_version_check
