apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: maximodb
spec:
  sid: MAXIMODB
  replicas: 1
  loadBalancer: true
  edition: enterprise
  adminPassword:
    secretName: oracledb-secrets
  charset: AL32UTF8
  pdbName: maximopdb1
  archiveLog: true
  initParams:
    pgaAggregateTarget: 512
    processes: 100
    sgaTarget: 1024
  image:
    pullFrom: container-registry.oracle.com/database/enterprise
    pullSecrets: oracle-regcred
  persistence:
    accessMode: ReadWriteOnce
    size: 200Gi
    storageClass: ibmc-block-gold