---
# 1. Check that we have the ocp vars defined
# -----------------------------------------------------------------------------
- name: "login : Fail if ocp_server, ocp_token, or ocp_skip_tls_verify are not provided"
  assert:
    that:
      - ocp_token is defined and ocp_token != ""
      - ocp_server is defined and ocp_server != ""
      - ocp_skip_tls_verify is defined and ocp_skip_tls_verify != ""
    fail_msg: "ocp_server, ocp_token, & ocp_skip_tls_verify must be provided together"


# 2. Login to OCP
# -----------------------------------------------------------------------------
- name: "login : Login to OCP"
  shell: oc login --token={{ ocp_token }} --server={{ ocp_server }} --insecure-skip-tls-verify={{ ocp_skip_tls_verify }}
  register: login_result
  retries: 5
  delay: 10 # seconds
  until: login_result.rc == 0

- name: "login : Debug OCP login"
  debug:
    msg: "{{ login_result.stdout_lines }}"
