---

# MAS instance and application
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_app_id: visualinspection

# Flag to control whether the SCC ClusterRole and ClusterRoleBinding are created.
# Set to false to skip RBAC setup (e.g. if a cluster admin pre-creates them).
mvi_setup_clusterrole: "{{ lookup('env', 'MVI_SETUP_CLUSTERROLE') | default('true', true) | bool }}"
