---

# BEGIN rollback
# The following steps will perform a roll back of the API key secret namespace change performed when upgrading from 9.1 to 9.2.
# If the secret is detected in the tenant namespace then it is assumed that a rollback is necessary.
# Remove this block when 9.1 is no longer supported.
- name: Roll back API key secret namespace change if necessary
  when:
    - aiservice_channel is defined
    - aiservice_channel.startswith('9.1.')
  block:
    - name: Check if API key secret exists in tenant namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ tenantNamespace }}"
        name: "{{ tenantNamespace }}----apikey-secret"
      register: tenant_api_secret_result
      no_log: true

    - name: Confirm if API key secret rollback is needed
      set_fact:
        is_api_key_rollback_needed: "{{ tenant_api_secret_result.resources | length == 1 | bool }}"

    - name: "Move tenant API key secret back to namespace {{ aiservice_namespace }}"
      when: is_api_key_rollback_needed
      kubernetes.core.k8s:
        state: present
        namespace: "{{ aiservice_namespace }}"
        definition: >
          {{ tenant_api_secret_result.resources[0] | ibm.mas_devops.remove_dict_keys(['status', 'metadata.namespace', 'metadata.creationTimestamp',
          'metadata.generation', 'metadata.resourceVersion', 'metadata.uid', 'metadata.ownerReferences']) | to_yaml }}

    - name: "Delete tenant API key secret from namespace {{ tenantNamespace }}"
      when: is_api_key_rollback_needed
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        namespace: "{{ tenantNamespace }}"
        name: "{{ tenantNamespace }}----apikey-secret"
        kind: Secret

    - name: Confirm if rollback was performed
      ansible.builtin.debug:
        msg: "Was tenant API key secret moved to namespace {{ aiservice_namespace  }}? .......... {{ is_api_key_rollback_needed }}"

# END rollback

- name: Set target namespace
  set_fact:
    target_namespace: "{{ (((aiservice_channel is defined) and aiservice_channel.startswith('9.1.')) or not requires_namespaced_tenant_operator) | ternary(aiservice_namespace, tenantNamespace) }}"

- name: "Create tenant CR"
  vars:
    annotation_dict: "{{ mas_annotations | string | ibm.mas_devops.getAnnotations() }}"
  kubernetes.core.k8s:
    state: present
    namespace: "{{ target_namespace }}"
    template: templates/aiservice/aiservicetenant.yml.j2

- name: "Wait for tenant CR to be ready"
  kubernetes.core.k8s_info:
    api_version: aiservice.ibm.com/v1
    name: "{{ tenantNamespace }}"
    namespace: "{{ target_namespace }}"
    kind: AIServiceTenant
  register: aiservicetenant_cr_result
  until:
    - aiservicetenant_cr_result.resources is defined and aiservicetenant_cr_result.resources | length == 1
    - aiservicetenant_cr_result.resources[0].status is defined
    - aiservicetenant_cr_result.resources | json_query('[*].status.conditions[?type==`Successful`][].status') | select ('match','True') | list | length == 1
  retries: 45 # approx 45 minutes before we give up
  delay: 60 # 1 minute

- name: "Copy secrets to namespace: {{ tenantNamespace }}"
  shell: 'oc get secret {{ item }} -n aiservice-{{ aiservice_instance_id }} -o yaml | sed "s/namespace: .*/namespace: {{ tenantNamespace }}/" | oc apply --force -f -'
  with_items:
    - km-s3-secret
    - "{{ aiservice_pull_secret_name }}"

- name: "Create network policy for predictor"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/tenant/ingress-allow-isvc.yml.j2"
