---
# MAS Suite Configuration
# -----------------------------------------------------------------------------
mas_domain: "{{ lookup('env', 'MAS_DOMAIN') }}"
mas_instance: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

# Namespace to install servicemesh gateway and routing resources.
servicemesh_gateway_namespace: "{{ lookup('env', 'SERVICEMESH_GATEWAY_NAMESPACE') | default('mas-'+mas_instance+'-servicemesh', true) }}"

gateway_strategy: "{{ lookup('env', 'GATEWAY_STRATEGY') | default('many_gateways', true) }}"
