#
## Database Admin Password Secret
apiVersion: v1
kind: Secret
metadata:
  name: db-admin-secret
  namespace: "{{ oracle_namespace }}"
type: Opaque
stringData:
  ## Specify your DB password here
  oracle_pwd:
