---
kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: sidb-scc
  namespace: "{{ oracle_namespace }}"
allowPrivilegedContainer: false
users:
  - system:serviceaccount:{{ oracle_namespace }}:sidb-sa
  - system:serviceaccount:{{ oracle_namespace }}:oracle-database-operator
runAsUser:
  type: MustRunAsRange
  uidRangeMin: 0
  uidRangeMax: 60000
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: MustRunAs
  ranges:
    - min: 0
      max: 60000
supplementalGroups:
  type: MustRunAs
  ranges:
    - min: 0
      max: 60000
volumes:
  - "*"
allowedCapabilities:
  - "*"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sidb-sa
  namespace: "{{ oracle_namespace }}"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-sidb-scc
  namespace: "{{ oracle_namespace }}"
rules:
  - apiGroups:
      - "*"
    resources:
      - securitycontextconstraints
    resourceNames:
      - sidb-scc
    verbs:
      - use

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-sidb-scc
  namespace: "{{ oracle_namespace }}"
subjects:
  - kind: ServiceAccount
    name: sidb-sa
roleRef:
  kind: Role
  name: use-sidb-scc
  apiGroup: rbac.authorization.k8s.io
