---
# Default values for MCPI configuration
operatorName: ibm-mas-cfg-mcpi
operatorVersion: "{{ lookup('env','OPERATOR_VERSION') }}"
targetPlatform: "{{ lookup('env','TARGET_PLATFORM') }}"
namespacePrefix: "mas-"

mcpi_default_http_port: 9443
mcpi_default_rsyslog_port: 10514
mcpi_default_route_enabled: true

# Configure whether MAS is set up to use multiple-subdomains
routingMode: "{{ lookup('env','ROUTING_MODE') | default('subdomain', True)}}"
manualRouteMgmt: "{{ lookup('env','MANUAL_ROUTE_MGMT') | default('false', True) | bool }}"

# Client certificate locations for MAS internal API authentication
# =============================================================================
clientCertFile: "/tmp/mas/certs/client/tls.crt"
clientKeyFile: "/tmp/mas/certs/client/tls.key"
serverCAFile: "/tmp/mas/certs/ca.crt"

