---
- hosts: localhost
  vars:
    cluster_name: practice
    fyre_nfs_sc_name: nfs-client
  tasks:
    - include_role:
        name: ibm.mas_devops.ocp_login

    - include_role:
        name: ibm.mas_devops.ocp_provision
        tasks_from: providers/fyre/nfs/install_nfs.yml
