---
- hosts: localhost
  any_errors_fatal: true

  vars:
    mirror_mode: "{{ lookup('env', 'MIRROR_MODE') | default ('direct', True) }}"
    mirror_cli: "{{ lookup('env', 'MIRROR_CLI') | default ('False', True) | bool }}"
    cli_version: "{{ lookup('env', 'CLI_VERSION') | default ('latest', True) }}"

  roles:
    # IBM Maximo CLI Container
    # -------------------------------------------------------------------------
    - role: ibm.mas_devops.mirror_extras_prepare
      when:
        - mirror_cli
        - mirror_mode != "from-filesystem"
      vars:
        extras_name: cli
        extras_version: "{{ cli_version }}"

    - role: ibm.mas_devops.mirror_images
      when: mirror_cli
      vars:
        manifest_name: extras_cli
        manifest_version: "{{ cli_version }}"
