---
# aiservice_odh/tasks/main.yml
# =============================================================================
# Main dispatcher for ODH actions
# Supports: install, uninstall

- name: "ODH: Debug properties"
  debug:
    msg:
      - "ODH action ............................ {{ odh_action }}"
      - "ODH namespace ......................... {{ odh_namespace }}"
      - "ODH channel ........................... {{ odh_channel }}"
      - "ODH model deployment type ............. {{ aiservice_odh_model_deployment_type }}"

# Perform the selected action
# -----------------------------------------------------------------------------
- include_tasks: "{{ odh_action }}/main.yml"
  when: odh_action in ['install', 'uninstall']

- name: "ODH: Invalid action"
  fail:
    msg: "Invalid ODH action '{{ odh_action }}'. Must be one of: install, uninstall"
  when: odh_action not in ['install', 'uninstall']
