---
# Extra images for Redis (Collaborate)
# These images are part of the IBM Maximo Collaborate product
extra_images:
  - name: assist/ema-redis
    registry: cp.icr.io/cp
    tag: 2.1.40
    digest: sha256:a07d618d43dc0d0fe7d476a227e5b27dde6e390bdbdf76ee3056f990367a6633

  - name: assist/ema-haproxy
    registry: cp.icr.io/cp
    tag: 2.1.40
    digest: sha256:0450aef3fee9e704dc06fa19f6bd801f7089621c6a8cd99fc4416623660d0c18

  - name: assist/ema-common-util
    registry: cp.icr.io/cp
    tag: 2.1.40
    digest: sha256:0ac3e42d08233080df0ad335d700ba4edcbd798f2617babe9401e487eadbfd67
