---
# podTemplates
# =============================================================================
# The podTemplates allows the user to override pod specific defaults such as
# resources, replicas, affinity and tolerations.
#
# DO NOT DEFINE anything under podTemplates. the entire podTemplates array will
# be overwritten by whatever is put into the CR spec
podTemplates: []

# supportedPodKeys
# =============================================================================
# Define the name(s) of operator(s) and their valid pod name(s), container(s)
# and/or initContainer(s). We need to pre-define these and pass it into the
# mas.util.update_pod_templates_status task to validate spec.podTemplates.
supportedPodKeys:
  ibm-mas-cfg-mcpi:
    mcpi:
      containers:
        - mcpi-viewer
        - mcpi-scripts

# Made with Bob
