{
 "title": "MongoDB Community",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_info{},cl_name)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(mongodb_info{cl_name=~\"$cluster\"}, pod)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(mongodb_info{cl_name=~\"$cluster\"}, mongodb_version)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "For reference documentation on the metrics included in this dashboard see <a target=\"_blank\" href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/\">MongoDB serverStatus command docs</a>"
   }
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
   "options": {
    "content": "<h2 style='color:#7393B3;font-weight:bold;text-align:center'>$version</h2>"
   }
  },
  {
   "title": "OPS Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
   "targets": [
    {
     "expr": "sum(\n  rate(mongodb_opcounters_command{cl_name=~\"$cluster\"}[1m]) +\n  rate(mongodb_opcounters_query{cl_name=~\"$cluster\"}[1m]) +\n  rate(mongodb_opcounters_insert{cl_name=~\"$cluster\"}[1m]) +\n  rate(mongodb_opcounters_delete{cl_name=~\"$cluster\"}[1m]) +\n  rate(mongodb_opcounters_update{cl_name=~\"$cluster\"}[1m]) +\n  rate(mongodb_opcounters_getmore{cl_name=~\"$cluster\"}[1m])\n)"
    }
   ]
  },
  {
   "title": "Read latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (\n  rate(mongodb_opLatencies_reads_latency{cl_name=~\"$cluster\"}[1m]) / \n  (rate(mongodb_opLatencies_reads_ops{cl_name=~\"$cluster\"}[1m]) > 0)\n)"
    }
   ]
  },
  {
   "title": "Write latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg (\n  rate(mongodb_opLatencies_writes_latency{cl_name=~\"$cluster\"}[1m]) / \n  (rate(mongodb_opLatencies_writes_ops{cl_name=~\"$cluster\"}[1m]) > 0)\n)"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "stat",
   "description": "Across all members of the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "targets": [
    {
     "expr": "sum (mongodb_connections_current{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "Across all members of the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "sum (mongodb_connections_active{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Available connections",
   "type": "stat",
   "description": "Across all members of the cluster",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mongodb_connections_available{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_extra_info_maximum_resident_set_kb{cl_name=~\"$cluster\"} / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "WiredTiger Cache Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(mongodb_wiredTiger_cache_maximum_bytes_configured{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Flow control",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg(mongodb_flowControl_enabled{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Flow control events",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 5 },
   "targets": [
    {
     "expr": "sum(mongodb_flowControl_isLaggedCount{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cached sessions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "sum(mongodb_logicalSessionRecordCache_activeSessionsCount{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Document Return Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_metrics_document_returned{cl_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Document Update Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_metrics_document_updated{cl_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Document Insert Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_metrics_document_inserted{cl_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Document Delete Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_metrics_document_deleted{cl_name=~\"$cluster\"}[1m]))"
    }
   ]
  },
  {
   "title": "Global Lock Queue",
   "type": "stat",
   "description": "Total number of operations queued waiting for a lock",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mongodb_globalLock_currentQueue_total{cl_name=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open cursors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 5 },
   "targets": [
    {
     "expr": "sum (mongodb_metrics_cursor_open_total{cl_name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Replica Set Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (pod) (mongodb_uptime{cl_name=~\"$cluster\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB Primary/Secondary",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_repl_isWritablePrimary{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ReplicaSet member states",
     "type": "timeseries",
     "description": "https://www.mongodb.com/docs/manual/reference/replica-states/\n\n- 0: startup\n- 1: primary\n- 2: secondary\n- 3: recovering\n- 5: startup2\n- 6: unknown\n- 7: arbiter\n- 8: down\n- 9: rollback\n- 10: removed",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_members_state{cl_name=~\"$cluster\"}\n",
       "legendFormat": "{{pod}} {{instance}}"
      }
     ]
    },
    {
     "title": "Current number of ops in oplog replication buffer",
     "type": "timeseries",
     "description": "- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.repl.buffer\">Replication buffer stats</a>",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      {
       "format": "short",
       "label": "OPS IN OPLOG REPLICATION BUFFER"
      }
     ],
     "targets": [
      {
       "expr": "mongodb_metrics_repl_buffer_count{cl_name=~\"$cluster\"}\n",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Election timeout metrics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "TIMEOUTS" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_electionMetrics_numCatchUpsTimedOut{cl_name=~\"$cluster\"})\n",
       "legendFormat": "catchup timeouts"
      },
      {
       "expr": "sum(mongodb_electionMetrics_electionTimeout_called{cl_name=~\"$cluster\"})\n",
       "legendFormat": "election timeouts"
      },
      {
       "expr": "sum(mongodb_electionMetrics_freezeTimeout_called{cl_name=~\"$cluster\"})\n",
       "legendFormat": "freeze timeouts"
      }
     ]
    },
    {
     "title": "Replication buffer size",
     "type": "timeseries",
     "description": "- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.repl.buffer\">Replication buffer stats</a>",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_metrics_repl_buffer_sizeBytes{cl_name=~\"$cluster\"}\n",
       "legendFormat": "current replication buffer size:  {{pod}}"
      },
      {
       "expr": "avg(mongodb_metrics_repl_buffer_maxSizeBytes{cl_name=~\"$cluster\"})\n",
       "legendFormat": "max size replication buffer"
      }
     ]
    },
    {
     "title": "Data read from replication sync source",
     "type": "timeseries",
     "description": "- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.repl.buffer\">Replication buffer stats</a>",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "Bps", "label": "NETWORK BANDWIDTH" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_metrics_repl_network_bytes{cl_name=~\"$cluster\"}[1m])\n",
       "legendFormat": "replication network utilization:  {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cursors and Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cursors",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "CURSORS" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_metrics_cursor_open_total{cl_name=~\"$cluster\"})",
       "legendFormat": "open cursors"
      },
      {
       "expr": "sum(mongodb_metrics_cursor_open_pinned{cl_name=~\"$cluster\"})",
       "legendFormat": "open cursors (pinned)"
      },
      {
       "expr": "sum(mongodb_metrics_cursor_open_noTimeout{cl_name=~\"$cluster\"})",
       "legendFormat": "open cursors (without timeout)"
      },
      {
       "expr": "sum(mongodb_metrics_cursor_timedOut{cl_name=~\"$cluster\"})",
       "legendFormat": "cursor timeouts"
      }
     ]
    },
    {
     "title": "Lock waiters",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "LOCK WAITERS" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_globalLock_currentQueue_readers{cl_name=~\"$cluster\"})",
       "legendFormat": "read lock waiters"
      },
      {
       "expr": "sum(mongodb_globalLock_currentQueue_writers{cl_name=~\"$cluster\"})",
       "legendFormat": "write lock waiters"
      },
      {
       "expr": "sum(mongodb_globalLock_currentQueue_total{cl_name=~\"$cluster\"})",
       "legendFormat": "total lock waiters"
      },
      {
       "expr": "sum(mongodb_globalLock_activeClients_total{cl_name=~\"$cluster\"})",
       "legendFormat": "active clients"
      }
     ]
    },
    {
     "title": "Lock acquisition rates",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short", "label": "LOCKS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_locks_Collection_acquireCount_W{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "collection exclusive(X) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Collection_acquireCount_w{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "collection intent exclusive(IX) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Collection_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "collection intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Database_acquireCount_W{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "database exclusive(X) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Database_acquireCount_w{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "database intent exclusive(IX) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Database_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "database intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Global_acquireCount_W{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "global exclusive(X) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Global_acquireCount_w{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "global  intent exclusive(IX) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Global_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "global intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_Mutex_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "mutex intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_oplog_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "oplog intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_oplog_acquireCount_w{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "oplog intent exclusive(IX) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_ParallelBatchWriterMode_acquireCount_W{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "ParallelBatchWriteMode exclusive(X) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_ParallelBatchWriterMode_acquireCount_r{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "ParallelBatchWriteMode intent shared (IS) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_ReplicationStateTransition_acquireCount_W{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "ReplicationStateTransition exclusive (X) locks"
      },
      {
       "expr": "sum(rate(mongodb_locks_ReplicationStateTransition_acquireCount_w{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "ReplicationStateTransition intent exclusive(IX) locks"
      }
     ]
    },
    {
     "title": "Lock wait time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(\n  mongodb_locks_ParallelBatchWriterMode_timeAcquiringMicros_W{cl_name=~\"$cluster\"} / \n  mongodb_locks_ParallelBatchWriterMode_acquireWaitCount_W{cl_name=~\"$cluster\"}\n)",
       "legendFormat": "average ParallelBatchWriteMode exclusive(X) lock wait time"
      },
      {
       "expr": "avg(\n  mongodb_locks_ParallelBatchWriterMode_timeAcquiringMicros_r{cl_name=~\"$cluster\"} / \n  mongodb_locks_ParallelBatchWriterMode_acquireWaitCount_r{cl_name=~\"$cluster\"}\n)",
       "legendFormat": "average ParallelBatchWriteMode intent shared (IS) lock wait time"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "CONNECTIONS" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections_current{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "CONNECTIONS" }
     ],
     "targets": [
      {
       "expr": "mongodb_connections_active{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Connection rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "CONNECTIONS / SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_connections_totalCreated{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pending connections",
     "type": "timeseries",
     "description": "Reference docs:\n- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.connections.exhaustHello\">Exhaust Hello Connections</a>\n- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.connections.exhaustIsMaster\">Exhaust IsMaster Connections</a>\n- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.connections.awaitingTopologyChanges\">Awaiting Topology Changes Connections</a>",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
     "yaxes": [
      { "format": "short", "label": "CONNECTIONS" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_connections_exhaustHello{cl_name=~\"$cluster\"})",
       "legendFormat": "exhaustHello connections"
      },
      {
       "expr": "sum(mongodb_connections_exhaustIsMaster{cl_name=~\"$cluster\"})",
       "legendFormat": "exhaustIsMaster connections"
      },
      {
       "expr": "sum(mongodb_connections_awaitingTopologyChanges{cl_name=~\"$cluster\"})",
       "legendFormat": "awaitingTopologyChanges connections"
      }
     ]
    },
    {
     "title": "Client TLS versions",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "TLS HANDSHAKES / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_transportSecurity_1_0{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "TLS 1.0"
      },
      {
       "expr": "sum(rate(mongodb_transportSecurity_1_1{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "TLS 1.1"
      },
      {
       "expr": "sum(rate(mongodb_transportSecurity_1_2{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "TLS 1.2"
      },
      {
       "expr": "sum(rate(mongodb_transportSecurity_1_3{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "TLS 1.3"
      },
      {
       "expr": "sum(rate(mongodb_transportSecurity_unknown{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "unknown"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg read latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "µs", "label": "AVG LATENCY" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (\n  rate(mongodb_opLatencies_reads_latency{cl_name=~\"$cluster\"}[1m]) / \n  (rate(mongodb_opLatencies_reads_ops{cl_name=~\"$cluster\"}[1m]) > 0)\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Avg write latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "µs", "label": "AVG LATENCY" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (\n  rate(mongodb_opLatencies_writes_latency{cl_name=~\"$cluster\"}[1m]) / \n  (rate(mongodb_opLatencies_writes_ops{cl_name=~\"$cluster\"}[1m]) > 0)\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Avg commands latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "µs", "label": "AVG LATENCY" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (\n  rate(mongodb_opLatencies_commands_latency{cl_name=~\"$cluster\"}[1m]) / \n  (rate(mongodb_opLatencies_commands_ops{cl_name=~\"$cluster\"}[1m]) > 0)\n)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operation Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "MongoDB Insert Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "INSERTS/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_insert{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB Query Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "QUERIES/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_query{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB Command Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "COMMANDS/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_command{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB Update Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "UPDATES/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_update{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB Delete Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "DELETES/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_delete{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "MongoDB GetMore Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "GETMORE/SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_opcounters_getmore{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Read concern levels",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "OPERATIONS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_local{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "local"
      },
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_available{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "available"
      },
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_none{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "none"
      },
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_linearizable{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "linearizable"
      },
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_majority{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "majority"
      },
      {
       "expr": "sum(rate(mongodb_opReadConcernCounters_snapshot{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "snapshot"
      }
     ]
    }
   ]
  },
  {
   "title": "Aggregation, Operator, Expression stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregation stage statistics",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (__name__) ({__name__=~\"mongodb_metrics_aggStageCounters_.*\", cl_name=~\"$cluster\"}))",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Operator statistics",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (__name__) ({__name__=~\"mongodb_metrics_operatorCounters_match_.*\", cl_name=~\"$cluster\"}))",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Expression statistics",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (__name__) ({__name__=~\"mongodb_metrics_operatorCounters_expressions_.*\", cl_name=~\"$cluster\"}))",
       "legendFormat": "{{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents and Commands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "DOCUMENTS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum by (pod) (rate(mongodb_metrics_document_returned{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "documents returned {{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(mongodb_metrics_document_updated{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "documents updated {{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(mongodb_metrics_document_inserted{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "documents inserted {{pod}}"
      },
      {
       "expr": "sum by (pod) (rate(mongodb_metrics_document_deleted{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "documents deleted {{pod}}"
      }
     ]
    },
    {
     "title": "Total commands issued",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 9, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "COMMANDS" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (__name__) ({__name__=~\"mongodb_metrics_commands_.*_total\", cl_name=~\"$cluster\"}))"
      }
     ]
    },
    {
     "title": "Failed commands",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "COMMANDS" }
     ],
     "targets": [
      {
       "expr": "topk(20, sum by (__name__) ({__name__=~\"mongodb_metrics_commands_.*_failed\", cl_name=~\"$cluster\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Scans and Conflicts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scans and conflict event rates",
     "type": "timeseries",
     "description": "- <a href=\"https://www.mongodb.com/doc-s/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.operation.scanAndOrder\">scanAndOrder</a>\n- <a href=\"https://www.mongodb.com/doc-s/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.operation.writeConflicts\">writeConflicts</a>",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "EVENTS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_metrics_operation_scanAndOrder{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "scanAndOrder"
      },
      {
       "expr": "sum(rate(mongodb_metrics_operation_writeConflicts{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "writeConflicts"
      },
      {
       "expr": "sum(rate(mongodb_metrics_queryExecutor_scanned{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "indexKeysScanned"
      },
      {
       "expr": "sum(rate(mongodb_metrics_queryExecutor_scannedObjects{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "documentsScanned"
      },
      {
       "expr": "sum(rate(mongodb_metrics_queryExecutor_collectionScans_total{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "collectionsScanned"
      }
     ]
    },
    {
     "title": "On disk record move events",
     "type": "timeseries",
     "description": "- <a href=\"https://www.mongodb.com/docs/manual/reference/command/serverStatus/#mongodb-serverstatus-serverstatus.metrics.record\">record moves</a>",
     "gridPos": { "h": 9, "w": 8, "x": 7, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "EVENTS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_metrics_record_moves{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "record moves"
      }
     ]
    }
   ]
  },
  {
   "title": "Network and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingress network bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_network_bytesIn{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Egress network bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_network_bytesOut{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Network Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "REQUESTS / SECOND" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_network_numRequests{cl_name=~\"$cluster\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Slow network operations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "OPERATIONS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_network_numSlowDNSOperations{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "slow DNS operations"
      },
      {
       "expr": "sum(rate(mongodb_network_numSlowSSLOperations{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "slow SSL operations"
      }
     ]
    },
    {
     "title": "Resident memory utiilization",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mem_resident{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Virtual memory utiilization",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mem_virtual{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Oplog and Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Oplog truncation events",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "TRUNCATION EVENTS" }
     ],
     "targets": [
      {
       "expr": "mongodb_oplogTruncation_truncateCount{cl_name=~\"$cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Oplog truncation processing time",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "avg(mongodb_oplogTruncation_totalTimeProcessingMicros{cl_name=~\"$cluster\"} / mongodb_oplogTruncation_truncateCount{cl_name=~\"$cluster\"})",
       "legendFormat": "average scanning time"
      },
      {
       "expr": "avg(mongodb_oplogTruncation_totalTimeTruncatingMicros{cl_name=~\"$cluster\"} / mongodb_oplogTruncation_truncateCount{cl_name=~\"$cluster\"})",
       "legendFormat": "average truncation time"
      }
     ]
    },
    {
     "title": "Current transaction states",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(mongodb_transactions_currentActive{cl_name=~\"$cluster\"})",
       "legendFormat": "active transactions"
      },
      {
       "expr": "sum(mongodb_transactions_currentInactive{cl_name=~\"$cluster\"})",
       "legendFormat": "inactive transactions"
      },
      {
       "expr": "sum(mongodb_transactions_currentOpen{cl_name=~\"$cluster\"})",
       "legendFormat": "open transactions"
      },
      {
       "expr": "sum(mongodb_transactions_currentPrepared{cl_name=~\"$cluster\"})",
       "legendFormat": "prepared transactions"
      }
     ]
    },
    {
     "title": "Transaction rates",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "TRANSACTIONS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_transactions_totalCommitted{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "transactions committed"
      },
      {
       "expr": "sum(rate(mongodb_transactions_totalAborted{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "transactions aborted"
      },
      {
       "expr": "sum(rate(mongodb_transactions_totalPrepared{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "transactions prepared"
      },
      {
       "expr": "sum(rate(mongodb_transactions_totalStarted{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "transactions started"
      }
     ]
    }
   ]
  },
  {
   "title": "WiredTiger",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "File system read latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "DISK READS" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_1_10_49ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (10 - 49 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_2_50_99ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (50 - 99 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_3_100_249ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (100 - 249 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_4_250_499ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (250 - 499 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_5_500_999ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (500 - 999 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_read_latency_histogram_bucket_6_1000ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk read latency (1000+ ms)"
      }
     ]
    },
    {
     "title": "File system write latency",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "DISK WRITES" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_1_10_49ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (10 - 49 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_2_50_99ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (50 - 99 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_3_100_249ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (100 - 249 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_4_250_499ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (250 - 499 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_5_500_999ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (500 - 999 ms)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_perf_file_system_write_latency_histogram_bucket_6_1000ms{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk write latency (1000+ ms)"
      }
     ]
    },
    {
     "title": "Cache <-> Disk bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_wiredTiger_cache_bytes_read_into_cache{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "disk -> cache (bytes/sec)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_cache_bytes_written_from_cache{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "cache -> disk (bytes/sec)"
      }
     ]
    },
    {
     "title": "Cache evictions",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short", "label": "EVICTIONS / SECOND" }
     ],
     "targets": [
      {
       "expr": "sum(rate(mongodb_wiredTiger_cache_eviction_calls_to_get_a_page{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "cache evictions"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_cache_eviction_calls_to_get_a_page_found_queue_empty{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "cache evictions (found queue empty)"
      },
      {
       "expr": "sum(rate(mongodb_wiredTiger_cache_eviction_calls_to_get_a_page_found_queue_empty_after_locking{cl_name=~\"$cluster\"}[1m]))",
       "legendFormat": "cache evictions (found queue empty after locking)"
      }
     ]
    }
   ]
  }
 ]
}