galaxy_info:
  author: David Parker (@durera) & André Marcelino (@andrercm)
  description: Install External Secrets Operator and configure IBM Secrets Manager integration
  company: IBM

  license: EPL-2.0

  min_ansible_version: "2.10"

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - rhocp
    - secrets
    - external-secrets

dependencies:
  - role: ibm.mas_devops.ansible_version_check

# Made with Bob
