---
dependencies: []

galaxy_info:
  role_name: suite_rbac
  author: IBM Maximo Application Suite Development Team
  description: Apply RBAC resources for MAS installation based on permission mode
  company: IBM
  license: EPL-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - ibm
    - mas
    - maximo
    - rbac
    - security
