---
# 1. Validate required inputs
# -----------------------------------------------------------------------------
- name: "Assert that mas_instance_id has been provided"
  assert:
    that: mas_instance_id is defined and mas_instance_id != ""
    fail_msg: "mas_instance_id property has not been set"

- name: "Assert that mas_config_dir has been provided"
  assert:
    that: mas_config_dir is defined and mas_config_dir != ""
    fail_msg: "mas_config_dir property has not been set"

# 2. Generate McpiCfg CR
# -----------------------------------------------------------------------------
- name: "Generate McpiCfg CR"
  ansible.builtin.template:
    src: mcpicfg.yml.j2
    dest: "{{ mas_config_dir }}/{{ mas_instance_id }}-mcpi-system.yml"
    mode: "664"
