---
# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Fail if required properties are not provided"
  assert:
    that:
      - ocp_release is defined and ocp_release != ""
      - mirror_working_dir is defined and mirror_working_dir != ""
    fail_msg: "One or more required properties are missing"

# 2. Perform Mirroring
# -----------------------------------------------------------------------------
- name: "Generate ImageSetConfiguration"
  ansible.builtin.template:
    src: imagesetconfiguration.yml.j2
    dest: "{{ mirror_working_dir }}/imageset-ocp{{ ocp_release }}.yml"
    mode: "664"

- name: "Debug Information"
  debug:
    msg:
      - "Command ...................... DOCKER_CONFIG={{ mirror_working_dir }} oc mirror --remove-signatures -c {{ mirror_working_dir }}/imageset-ocp{{ ocp_release }}.yml file:///{{ mirror_working_dir }} --v2"
      - "Log File ..................... {{ mirror_working_dir }}/logs/mirror-to-filesystem-ocp{{ ocp_release }}.log"

- name: "Mirror Red Hat content from source registry to filesystem"
# Important: We have added "--remove-signatures" temporarily due to a problem in the Red Hat Certified operator catalog
# This is the only way we can get image mirroring working.  We will remove this as soon as Red Hat fix the operator catalog
  shell: >
    DOCKER_CONFIG={{ mirror_working_dir }} oc mirror --remove-signatures -c {{ mirror_working_dir }}/imageset-ocp{{ ocp_release }}.yml file:///{{ mirror_working_dir }} --v2 &> {{ mirror_working_dir }}/logs/mirror-to-filesystem-ocp{{ ocp_release }}.log
