---
- name: "Service Mesh: Debug properties"
  debug:
    msg:
      - "Service Mesh action ......................... {{ servicemesh_action }}"
      - "Service Mesh channel................... {{ servicemesh_channel }}"
      - "Service Mesh namespace ................... {{ servicemesh_namespace }}"

# 1. Perform the selected action
# -----------------------------------------------------------------------------
# Three actions are supported:
# - install
# - install-kiali
# - uninstall
- include_tasks: "{{ servicemesh_action }}/main.yml"
  when: servicemesh_action in ['install', 'uninstall', 'install-kiali']
