---
galaxy_info:
  author: Társis Augusto Rodrigues Parreiras
  description: Deploy External Secrets Operator for Kubernetes secret management
  company: IBM
  license: EPL-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - kubernetes
    - openshift
    - secrets
    - eso
    - external_secrets_operator
    - helm

dependencies: []

# Made with Bob
