---
# aiservice_rhoai/tasks/main.yml
# =============================================================================
# Main dispatcher for RHOAI actions
# Supports: install, uninstall

- name: "RHOAI: Debug properties"
  debug:
    msg:
      - "RHOAI action .......................... {{ rhoai_action }}"
      - "RHOAI namespace ....................... {{ rhoai_namespace }}"
      - "RHOAI channel ......................... {{ rhoai_channel }}"
      - "RHOAI model deployment type ........... {{ aiservice_rhoai_model_deployment_type }}"

# Perform the selected action
# -----------------------------------------------------------------------------
- include_tasks: "{{ rhoai_action }}/main.yml"
  when: rhoai_action in ['install', 'uninstall']

- name: "RHOAI: Invalid action"
  fail:
    msg: "Invalid RHOAI action '{{ rhoai_action }}'. Must be one of: install, uninstall"
  when: rhoai_action not in ['install', 'uninstall']
