---
- name: "Create image-mirror for {{ item.source }}"
  ansible.builtin.shell: |
    rosa create image-mirror --cluster="{{ rosa_hcp_cluster_name }}" \
    --source="{{ item.source }}" \
    --mirrors="{{ item.mirrors | join(",") }}"

- name: "Check if {{ item.source }} was added to 'cluster' ImageDigestMirrorSet"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ImageDigestMirrorSet
    name: cluster
  until:
    - cluster_idms.resources[0].spec.imageDigestMirrors is defined
    - cluster_idms.resources[0].spec.imageDigestMirrors | length > 0
    - cluster_idms.resources[0].spec.imageDigestMirrors | selectattr('source', 'contains', item.source) | first
  retries: 30
  delay: 10
  register: cluster_idms
