---

# 1. Read the CA cert from the file
# -----------------------------------------------------------------------------
- name: Read the private registry CA cert
  set_fact:
    registry_private_ca_crt: "{{ lookup('file', registry_private_ca_file) replace('\n', '\\n') }}"
  no_log: true

# 2. Create the additional_trusted_ca.json
# A JSON file containing the registry hostname as the key, and the PEM-encoded
# certificate as the value, for each additional registry CA to trust.
# -----------------------------------------------------------------------------
- name: Create additional_trusted_ca.json from a template
  ansible.builtin.template:
    src: templates/additional_trusted_ca.json.j2
    dest: /tmp/additional_trusted_ca.json
    mode: preserve

# 3. Update or edit the image registry for the cluster
# Patches the cluster config to use this configmap in spec.additionalTrustedCA
# -----------------------------------------------------------------------------
- name: Patch cluster config with additional_trusted_ca.json
  ansible.builtin.shell:  |
    rosa login && \
    yes | \
    rosa edit cluster \
    --registry-config-additional-trusted-ca /tmp/additional_trusted_ca.json \
    -c {{ rosa_hcp_cluster_name }}

# Not sure how to get the exact name of the additionalTrustedCA
- name: "Check if additional_trusted_ca was added to 'cluster' Image"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Image
    name: cluster
  until:
    - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name is defined
    - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name != ""
  retries: 30
  delay: 10
  register: cluster_image_lookup
