---

# 1. Read the CA cert from the file
# -----------------------------------------------------------------------------
- name: "Read the private registry CA cert"
  set_fact:
    registry_private_ca_crt: "{{ lookup('file', registry_private_ca_file) | replace('\n', '\\n') }}"
  no_log: true

# 2. Create the additional_trusted_ca.json
# A JSON file containing the registry hostname as the key, and the PEM-encoded
# certificate as the value, for each additional registry CA to trust.
# -----------------------------------------------------------------------------
- name: "Create additional_trusted_ca.json from a template"
  ansible.builtin.template:
    src: templates/additional_trusted_ca.json.j2
    dest: "{{ ocp_idms_working_dir }}/additional_trusted_ca.json"
    mode: preserve

# 3. Check for existing additionalTrustedCA in openshift-config
# -----------------------------------------------------------------------------
- name: "Set facts"
  ansible.builtin.set_fact:
    additional_trusted_ca_exists: false
    last_additional_trusted_ca_name: ""

- name: "Lookup 'cluster' Image resource"
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Image
    name: cluster
  register: cluster_image_lookup

- name: "Set last_additional_trusted_ca_name from cluster_image_lookup"
  when:
    - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name is defined
    - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name != ""
  block:
  - name: "Lookup registry-additional-ca configmap"
    kubernetes.core.k8s_info:
      api_version: v1
      kind: ConfigMap
      namespace: openshift-config
      name: "{{ cluster_image_lookup.resources[0].spec.additionalTrustedCA.name }}"
    register: registry_additional_ca_cfgmap_lookup

  - name: "Update last_additional_trusted_ca_name"
    when:
      - registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] is defined
      - registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] != ""
      - (registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] | replace('\n', '\\n')) != registry_private_ca_crt
    ansible.builtin.set_fact:
      last_additional_trusted_ca_name: "{{ cluster_image_lookup.resources[0].spec.additionalTrustedCA.name }}"
  
  - name: "Check if additional_trusted_ca already exists"
    when:
      - registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] is defined
      - registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] != ""
      - (registry_additional_ca_cfgmap_lookup.resources[0].data[registry_private_host] | replace('\n', '\\n')) == registry_private_ca_crt
    ansible.builtin.set_fact:
      additional_trusted_ca_exists: true

# 4. Update the image registry for the cluster
# Patches the cluster config to use this configmap in spec.additionalTrustedCA
# -----------------------------------------------------------------------------
- name: "Add additional_trusted_ca.json"
  when: not additional_trusted_ca_exists
  block:
    - name: "Patch cluster config with additional_trusted_ca.json"
      ansible.builtin.shell: |
        rosa edit cluster \
        --registry-config-allowed-registries="{{ registry_private_host }}" \
        --registry-config-additional-trusted-ca="{{ ocp_idms_working_dir }}"/additional_trusted_ca.json \
        --cluster="{{ rosa_hcp_cluster_name }}" \
        -y

    - name: "Check if additional_trusted_ca was added to 'cluster' Image"
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Image
        name: cluster
      until:
        - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name is defined
        - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name != ""
        - cluster_image_lookup.resources[0].spec.additionalTrustedCA.name != last_additional_trusted_ca_name
      retries: 30
      delay: 10
      register: cluster_image_lookup

    # Cleanup
    - name: "Delete {{last_additional_trusted_ca_name }} configmap in openshift-config"
      when: last_additional_trusted_ca_name != ""
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: ConfigMap
        namespace: openshift-config
        name: "{{ last_additional_trusted_ca_name }}"

    - name: "Delete local copy of additional_trusted_ca.json"
      ansible.builtin.file:
        path: "{{ ocp_idms_working_dir }}/additional_trusted_ca.json"
        state: absent
