---

# 1. Update default cluster image pull secret
# https://docs.redhat.com/en/documentation/red_hat_openshift_service_on_aws/4/html/images/managing-images#images-update-global-pull-secret_using-image-pull-secrets
# This results in the following states of the each pull secret:
#   Original: immutable (pull secret in openshift-config)
#   Additional: mutable (pull secret in kube-system)
#   Global: final state of both the original and additional pull secrets
# =============================================================================
- name: Set new_auth_base64
  ansible.builtin.set_fact:
    new_auth_base64: "{{ registry_authentication | b64encode }}"

- name: Set new_auth_registry
  ansible.builtin.set_fact:
    new_auth_registry: "{{ {registry_host: {'auth': new_auth_base64}} }}"

- name: Check if additional-pull-secret secret in kube-system exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: additional-pull-secret
    namespace: kube-system
  register: additional_pull_secret_lookup

- name: Set additional-pull-secret fact from lookup
  when:
    - additional_pull_secret_lookup.resources is defined
    - additional_pull_secret_lookup.resources | length > 0
    - additional_pull_secret_lookup.resources[0].data['.dockerconfigjson'] is defined
  ansible.builtin.set_fact:
    additional_pull_secret: "{{ additional_pull_secret_lookup.resources[0].data['.dockerconfigjson'] | b64decode | from_json }}"

- name: Set additional-pull-secret in kube-system
  when: not (additional_pull_secret['auths'] is defined and
            additional_pull_secret['auths'][registry_host] is defined and
            additional_pull_secret['auths'][registry_host]['auth'] is defined and
            additional_pull_secret['auths'][registry_host]['auth'] == new_auth_base64)
  block:
    - name: Prepare stringData content
      ansible.builtin.set_fact:
        content: "{{ {'auths': additional_pull_secret['auths'] | default({}) | combine(new_auth_registry, recursive=true, list_merge='append_rp')} }}"

    - name: "Apply additional-pull-secret secret in kube-system"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/dockerconfigjson
          metadata:
            name: additional-pull-secret
            namespace: kube-system
          stringData:
            .dockerconfigjson: "{{ content | to_json | string }}"
