---
# Default application spec for Monitor
_settings_storage:
  storageClass: "{{ mas_app_settings_monitor_pvc_storage_class | default('', true) }}"
  storageClassSize: "{{ mas_app_settings_monitor_pvc_size }}"

mas_app_spec:
  bindings:
    mongo: system
  settings:
    deployment:
      size: "{{ mas_app_settings_monitor_deployment_size }}"
    storage: "{{ _settings_storage }}"
