---
# The image pull secret is needed to pull Oracle Entrprise edition runtime image
- name: "Admin Password : Create oracle-admin secret in {{ oracle_operator_namespace }} namespace"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "oracle-admin"
        namespace: "{{ oracle_operator_namespace }}"
      stringData:
        oracle_pwd: "{{ oracle_admin_pwd }}"
