---
# 1. Load default storage classes (if not provided by the user)
# -----------------------------------------------------------------------------
- include_tasks: tasks/determine-storage-classes.yml


# 2. Provide debug
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "AMQ Streams namespace ................. {{ kafka_namespace }}"

# 3. Install AMQ Streams operator
# -----------------------------------------------------------------------------
- name: "Install Oracle Database Operator"
  kubernetes.core.k8s:
    apply: yes
    template: templates/subscription.yml.j2

- name: "Create RBAC: oracle-database-operator"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/sidb_rbac.yml') }}"

- name: "Create dedicated route: oracle-database-operator"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/tlsroute.yml.j2') }}"