---
# 1. Load default storage classes (if not provided by the user)
# -----------------------------------------------------------------------------
- include_tasks: tasks/determine-storage-classes.yml


# 2. Provide debug
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "AMQ Streams namespace ................. {{ kafka_namespace }}"
      - "AMQ Streams kafka version ............. {{ kafka_version }}"
      - "AMQ Streams cluster name .............. {{ kafka_cluster_name }}"
      - "AMQ Streams cluster size .............. {{ kafka_cluster_size }}"
      - "AMQ Streams kafka storage class ....... {{ kafka_storage_class }}"
      - "AMQ Streams kafka storage size ........ {{ kafka_storage_size }}"
      - "AMQ Streams zookeeper storage class ... {{ zookeeper_storage_class }}"
      - "AMQ Streams zookeeper storage size .... {{ zookeeper_storage_size }}"
      - "AMQ Streams MAS user .................. {{ kafka_user_name }}"

# 3. Install AMQ Streams operator
# -----------------------------------------------------------------------------
- name: "Install Oracle Database Operator"
  kubernetes.core.k8s:
    apply: yes
    template: templates/subscription.yml.j2