---
# 1. Setup OCP IDMS
# -----------------------------------------------------------------------------
- name: Run the specified action
  ansible.builtin.include_tasks: "tasks/{{ ocp_idms_action }}/main.yml"
  when:
    - ocp_idms_action in ["default", "rosa_hcp"]
