---
# 1. Check for common required parameters
# -----------------------------------------------------------------------------
- name: "Check for required parameters"
  assert:
    that:
      - registry_private_host is defined and registry_private_host != ""

- name: "Check if registry_private_host is valid"
  ansible.builtin.assert:
    that: registry_private_host is regex('^[-._a-zA-Z0-9]+$')
    fail_msg: "registry_private_host must consist of alphanumeric characters, -, _ or ."


# 2. Setup OCP IDMS
# -----------------------------------------------------------------------------
# Run special case for rosa-hcp
- name: Run ocp_idms for rosa-hcp
  ansible.builtin.include_tasks: "tasks/rosa-hcp/main.yml"
  when:
    - cluster_type is defined
    - cluster_type == "rosa-hcp"

# Run default
- name: Run ocp_idms
  ansible.builtin.include_tasks: "tasks/default/main.yml"
  when: cluster_type is not defined or (cluster_type is defined and cluster_type != "rosa-hcp")
