---
# Whether to perform an install or an uninstall
servicemesh_action: "{{ lookup('env', 'SERVICEMESH_ACTION') | default('install', true) }}"

servicemesh_channel: "{{ lookup('env', 'SERVICEMESH_CHANNEL') | default('stable-3.3', true) }}"
servicemesh_starting_csv: "{{ lookup('env', 'SERVICEMESH_CSV') | default('servicemeshoperator3.v3.3.1', true) }}"

# Settings to set servicemesh locations
servicemesh_namespace: "{{ lookup('env', 'SERVICEMESH_NAMESPACE') | default('istio-system', true) }}"
servicemesh_cni_namespace: "{{ lookup('env', 'SERVICEMESH_CNI_NAMESPACE') | default('istio-cni', true) }}"
servicemesh_ingress_namespace: "{{ lookup('env', 'SERVICEMESH_INGRESS_NAMESPACE') | default('istio-ingress', true) }}"
# Settings to set servicemesh configuration
install_kiali: "{{ lookup('env', 'INSTALL_KIALI') | default('false', true) | bool}}"
kiali_channel: "{{ lookup('env', 'KIALI_CHANNEL') | default('stable', true) }}"
kiali_starting_csv: "{{ lookup('env', 'KIALI_CSV') | default('kiali-operator.v2.22.1', true) }}"

istio_version: "{{ lookup('env', 'ISTIO_VERSION') | default('v1.28.5', true) }}"
