---
- name: "Service Mesh Domain Config : Debug properties"
  debug:
    msg:
      - "MAS Suite Domain ......................... {{ mas_domain }}"
      - "MAS Suite Instance ....................... {{ mas_instance }}"
      - "Service Mesh Ingress namespace ........... {{ servicemesh_gateway_namespace }}"
      - "Gateway Strategy ......................... {{ gateway_strategy }}"

- name: "Create Gateway Namespace"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/namespace.yml.j2"

# Process the different application namespaces..
# -----------------------------------------------------------------------------
- name: "Get Config Maps in {{mas_instance}} namespaces"
  include_tasks: "tasks/create_gateways_per_namespace.yml"
  loop:
    - core
    - facilities
    - iot
    - manage
    - monitor
    - optimizer
    - predict
  loop_control:
    loop_var: ns_suffix

