---
# Uninstall CP4D Services
# This common task deletes CP4D Custom Services

# 1. Delete Service Custom Resources
# -----------------------------------------------------------------------------
- name: "Delete {{ cpd_service }} Custom Resource"
  when: cpd_service in installed_services
  kubernetes.core.k8s:
    state: absent
    api_version: "{{ cpd_service_info[cpd_service].cr_api_version }}"
    kind: "{{ cpd_service_info[cpd_service].cr_kind }}"
    namespace: "{{ cpd_instance_namespace }}"
    name: "{{ cpd_service_info[cpd_service].cr_name }}"
    wait: true
    wait_timeout: "{{ cpd_uninstall_wait_timeout }}"

# 2. Wait for Service CR to be deleted
# -----------------------------------------------------------------------------
- name: "Wait for {{ cpd_service }} CR to be deleted"
  when: cpd_service in installed_services
  kubernetes.core.k8s_info:
    api_version: "{{ cpd_service_info[cpd_service].cr_api_version }}"
    kind: "{{ cpd_service_info[cpd_service].cr_kind }}"
    namespace: "{{ cpd_instance_namespace }}"
    name: "{{ cpd_service_info[cpd_service].cr_name }}"
  register: service_cr_status
  until: service_cr_status.resources | length == 0
  retries: 60  # 10 minutes (60 * 10s)
  delay: 10