---
# 1. Debug Info
# -----------------------------------------------------------------------------
- name: "Debug configuration actions"
  debug:
    msg:
      - "ocp_update_ciphers_for_semeru ........... {{ ocp_update_ciphers_for_semeru }}"
      - "ocp_ingress_update_timeouts ............ {{ ocp_ingress_update_timeouts }}"
      - "ocp_ingress_namespace_ownership ........ {{ ocp_ingress_namespace_ownership if ocp_ingress_namespace_ownership != '' else 'Not set' }}"
      - "ocp_ingress_controller_name ............ {{ ocp_ingress_controller_name }}"
      - "ocp_operatorhub_disable_redhat_sources . {{ ocp_operatorhub_disable_redhat_sources }}"

# 2. Update API Server
# -----------------------------------------------------------------------------
- include_tasks: update-ciphers-for-semeru.yml
  when: ocp_update_ciphers_for_semeru

# 3. Update Ingress Controller (timeouts and/or namespace ownership)
# -----------------------------------------------------------------------------
- include_tasks: update-ingress-controller.yml
  when: ocp_ingress_update_timeouts or ocp_ingress_namespace_ownership != ''

# 4. Update OperatorHub
# -----------------------------------------------------------------------------
- include_tasks: update-operatorhub.yml
  when: ocp_operatorhub_disable_redhat_sources

# 5. For IPv6 testing, lookup network
- name: Lookup network for IPv6 testing
  kubernetes.core.k8s:
    api_version: config.openshift.io/v1
    kind: Network
    name: "cluster"
  when:
    - ocp_enable_ipv6 == true
  register: _network

# 6. For IPv6 testing, enable dual stack networking
- name: "Enable dual stack networking"
  kubernetes.core.k8s_json_patch:
    kind: Network
    name: "cluster"
    api_version: config.openshift.io/v1
    patch:
      - op: add
        path: /spec/clusterNetwork/-
        value:
          cidr: fd01::/48
          hostPrefix: 64
      - op: add
        path: /spec/serviceNetwork/-
        value: fd02::/112
  register: _dualstackNetworkAddr
  when:
    - ocp_enable_ipv6 == true
    - "'fd01::/48' not in (_network.result.spec.clusterNetwork | map(attribute='cidr') | list)"
