---
# Create Redis Secrets
# =============================================================================

- name: "Create ibm-entitlement secret for image pull"
  when:
    - artifactory_username is defined
    - artifactory_token is defined
  vars:
    artifactoryAuthStr: "{{ artifactory_username }}:{{ artifactory_token }}"
    artifactoryAuth: "{{ artifactoryAuthStr | b64encode }}"
    content:
      - '{"auths":{"docker-na-public.artifactory.swg-devops.com/wiotp-docker-local": {"username":"{{ artifactory_username }}","password":"{{ artifactory_token }}","auth":"{{ artifactoryAuth }}"}'
      - ',"docker-na-proxy-svl.artifactory.swg-devops.com/wiotp-docker-local": {"username":"{{ artifactory_username }}","password":"{{ artifactory_token }}","auth":"{{ artifactoryAuth }}"}'
      - ',"docker-na-proxy-rtp.artifactory.swg-devops.com/wiotp-docker-local": {"username":"{{ artifactory_username }}","password":"{{ artifactory_token }}","auth":"{{ artifactoryAuth }}"}'
      - ',"cp.icr.io/cp": {"username":"cp","password":"{{ ibm_entitlement_key }}","auth":"{{ (\"cp:\" + ibm_entitlement_key) | b64encode }}"}'
      - "}"
      - "}"
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: ibm-entitlement
        namespace: "{{ redis_namespace }}"
      stringData:
        .dockerconfigjson: "{{ content | join('') | string }}"

- name: "Check if Redis credentials secret exists"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ redis_credentials_secret_name }}"
    namespace: "{{ redis_namespace }}"
  register: secret_info

- name: "Create Redis credentials secret"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ redis_credentials_secret_name }}"
        namespace: "{{ redis_namespace }}"
        labels:
          app: "{{ redis_instance_name }}"
          mas.ibm.com/instanceId: "{{ mas_instance_id }}"
          mas.ibm.com/component: "redis"
      type: Opaque
      stringData:
        password: "{{ redis_password }}"
  when: secret_info.resources | length == 0
  no_log: true

- name: "Display secret status"
  debug:
    msg:
      - "IBM Entitlement secret created in {{ redis_namespace }} namespace"
      - "Redis credentials secret '{{ redis_credentials_secret_name }}' is ready"
