---
# 1. Create Gateway deployment, service etc
# -----------------------------------------------------------------------------
- name: "expand the route reference data"
  set_fact:
    route_reference : "{{ routeref_configmap.data['route.yml'] | from_yaml }}"

- debug: 
    msg:
      - "routeref_configmap.data['route.yml'] ..... {{ routeref_configmap.data['route.yml'] }}"
      - "route_reference ..... {{ route_reference }}"

- name: "determine gateway name"
  set_fact:
    # gateway_name: "gateway-{{ routeref_configmap.metadata.name | regex_replace('^routeref-','')}}"
    gateway_name: "gateway-{{ route_reference.metadata.name }}"

- debug: 
    msg:
      - "gateway_name ..... {{ gateway_name }}"


- name: "install : Set facts for Virtual Service"
  set_fact:
    route: "{{ route_reference.metadata.name | regex_replace('^'+mas_instance+'-', '') }}"
    service_name: "{{ route_reference.spec.to.name }}"
    service_namespace: "{{ route_reference.metadata.namespace }}"
    gateway_service: "{{ gateway_name }}"
    route_host: "{{ route_reference.spec.host }}"
    route_path: "{{ route_reference.spec.path }}"
    route_tls: "{{ route_reference.spec.tls }}"

- debug: 
    msg:
      - "route_tls ..... {{ route_tls }}"

- name: Initialize fixed_tls
  set_fact:
    fixed_tls: {}

- name: Fix newlines for each certificate field
  set_fact:
    fixed_tls: "{{ fixed_tls | combine({item.key: item.value | replace('\\n', '\n')}) }}"
  loop: "{{ route_tls | dict2items }}"
  when: item.value is string

# - name: Fix newlines for all tls certificate fields
#   set_fact:
#     fixed_tls: >-
#       {{
#         route_tls | dict2items |
#         map('combine', {'value': item.value | replace('\\n', '\n') if 'CERTIFICATE' in (item.value | string) else item.value}) |
#         items2dict
#       }}

- debug: 
    msg:
      - "fixed_tls ..... {{ fixed_tls }}"      

- name: "install : Create Service Mesh Gateway Deployment"
  kubernetes.core.k8s:
    template: "templates/gateway-deployment.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "install : Create Service Mesh Gateway Service"
  kubernetes.core.k8s:
    template: "templates/gateway-service.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "install : Create Service Mesh Gateway CR"
  kubernetes.core.k8s:
    template: "templates/gateway-passthrough-cr.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "install : Set facts for Virtual Service"
  set_fact:
    route: "{{ route_reference.metadata.name | regex_replace('^'+mas_instance+'-', '') }}"
    service_name: "{{ route_reference.spec.to.name }}"
    service_namespace: "{{ route_reference.metadata.namespace }}"
    gateway_service: "{{ gateway_name }}"
    route_host: "{{ route_reference.spec.host }}"
    route_path: "{{ route_reference.spec.path }}"
    route_tls: "{{ route_reference.spec.tls }}"

- name: "install : Create Virtual Service for {{route}} to {{service_name}}"
  kubernetes.core.k8s:
    template: "templates/virtual-service.yml.j2"
    wait: yes
    wait_timeout: 120

- debug: 
    msg:
      -  "ROIUTE TEMPLATE: {{ lookup('template','templates/route.yml.j2') }}"

- name: "install : Create Route for {{route}} to gateway"
  kubernetes.core.k8s:
    template: "templates/route.yml.j2"
    wait: yes
    wait_timeout: 120
