---
# 1. Create a Gateway instance for each route.
# -----------------------------------------------------------------------------

- name: "Service Mesh Domain Config: Create Gateway for domain"
  include_tasks: "tasks/many_gateways/create_gateway_for_route_reference.yml"
  loop: "{{ routeref_configmaps }}"
  loop_control:
    loop_var: routeref_configmap
  no_log: true
