---
# 1. Create Gateway deployment, service etc
# -----------------------------------------------------------------------------
- name: "create gateway : Expand the route reference data"
  set_fact:
    route_reference : "{{ routeref_configmap.data['route.yml'] | from_yaml }}"

- name: "create gateway : Determine gateway name"
  set_fact:
    route: "{{ ns_suffix }}-{{ route_reference.metadata.name | regex_replace(mas_instance+'-', '') }}"

- name: "create gateway : Determine gateway name"
  set_fact:
    gateway_name: "gateway-{{ route }}"

- debug:
    msg:
      - "gateway_name ..... {{ gateway_name }}"

- name: "create gateway : Set facts for Virtual Service"
  set_fact:
    service_name: "{{ route_reference.spec.to.name }}"
    service_namespace: "{{ route_reference.metadata.namespace | default( targetNamespace )}}"
    gateway_service: "{{ gateway_name }}"
    route_host: "{{ route_reference.spec.host }}"
    route_path: "{{ route_reference.spec.path | default('')}}"
    route_tls: "{{ route_reference.spec.tls }}"
    target_port_name: "{{ route_reference.spec.port.targetPort }}"
    port_number: 443
    target_port_number: 8443

- set_fact:
    port_number: 8883
    target_port_number: 8883
  when: target_port_name == "mqtts"

- set_fact:
    port_number: 3000
    target_port_number: 3000
  when: target_port_name == 3000

# collaborateext
- set_fact:
    port_number: 3000
    target_port_number: 3000
  when: target_port_name == "http"

# Monitor services
- set_fact:
    port_number: 9443
    target_port_number: 9443
  when: target_port_name == 9443

- debug:
    msg:
      - "service_name ........... {{ service_name }}"
      - "service_namespace ...... {{ service_namespace }}"
      - "gateway_service ........ {{ gateway_service }}"
      - "route_host ............. {{ route_host }}"
      - "route_path ............. {{ route_path }}"
      - "route_tls.termination .. {{ route_tls.termination }}"
      - "gateway_name ........... {{ gateway_name }}"
      - "target_port_name ....... {{ target_port_name }}"
      - "port_number ............ {{ port_number }}"
      - "target_port_number ..... {{ target_port_number }}"

- name: "create gateway : Create Service Mesh Gateway Deployment"
  kubernetes.core.k8s:
    template: "templates/gateway-deployment.yml.j2"
    wait: yes
    wait_timeout: 300

- name: "create gateway : Create Service Mesh Gateway Service"
  kubernetes.core.k8s:
    template: "templates/gateway-service.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "create gateway : Create Service Mesh Gateway CR"
  kubernetes.core.k8s:
    template: "templates/gateway-passthrough-cr.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "create gateway : Create Virtual Service for {{route}} to {{service_name}}"
  kubernetes.core.k8s:
    template: "templates/virtual-service.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "create gateway : Create Route for {{route}} to gateway"
  when: service_name == "collaboratecollaborateext-service"
  kubernetes.core.k8s:
    template: "templates/route_reencrypt_collaborate.yml.j2"
    wait: yes
    wait_timeout: 120

- name: "create gateway : Create Route for {{route}} to gateway"
  when: service_name != "collaboratecollaborateext-service"
  kubernetes.core.k8s:
    template: "templates/route_{{route_tls.termination}}.yml.j2"
    wait: yes
    wait_timeout: 120
