catsrc_info:
  cpd_platform:
    - catalog_name: cpd-platform
      catalog_display_name: ibm-cp-datacore-6.4.0-50
      name: cpopen/ibm-cpd-platform-operator-catalog
      registry: icr.io
      tag: 6.4.0-50
      digest: sha256:0a63f6bf9c312efc3daca05a657c70f300eaef7f5a36055753b11fcf014688ca
  cpfs:
    - catalog_name: opencloud-operators
      catalog_display_name: ibm-cp-common-services-4.17.0
      name: cpopen/ibm-common-service-catalog
      registry: icr.io
      tag: 4.17.0
      digest: sha256:de97dd2a35b4c58da9b7ad5d89976d7a4184541e2e0a78a1c71e441a0105ce6e
  zen:
    - catalog_name: ibm-zen-operator-catalog
      catalog_display_name: ibm-zen-6.4.0-92
      name: cpopen/ibm-zen-operator-catalog
      registry: icr.io
      digest: sha256:9a02519e5ab679f0807fc5b7cfc5fc96242961bee0e1d3144012d33e925e6a99
      tag: 6.4.0-92
