notifications.mail.smtp.email.host=
notifications.mail.smtp.email.auth=
notifications.mail.smtp.email.username=
notifications.mail.smtp.email.password=
notifications.mail.smtp.email.port=
notifications.mail.smtp.email.security.protocol=
notifications.mail.smtp.email.ssl.protocols=
notification.mail.smtp.ssl.checkserveridentity=true
notifications.mail.smtp.email.id=
notifications.mail.smtp.email.label=Workflow Notification
notifications.mail.smtp.email.domain=
mail.imaps.ssl.key=
mail.imaps.ssl.port=993
BRAVA_SERVER_URL=
BRAVA_EXCLUDE_LIST=*
ENABLE_CMIS=N
CMIS_URL=
CMIS_USER=
CMIS_PW=
CMIS_STORE=
CMIS_ROOT=
AGENTS_NOT_ALLOWED=
CadIntegratorLoad=100.0
CadIntegratorMaxThreads=5
DataImportAgentLoad=100.0
DataImportAgentMaxThreads=6
SchedulerAgentLoad=100.0
SchedulerAgentMaxThreads=3
WFAgentLoad=100.0
WFAgentMaxThreads=80
ReportQueueAgentLoad=100.0
ReportQueueAgentMaxThreads=2
MSExchangeSubscriptionsThreadpoolLoad=100.0
AGENT_STALE_TIME_IN_SECONDS=60
WF_AGENT_MAX_ACTIVE_PER_USER=70
WF_INSTANCE_SAVE=ERRORS_ONLY
WF_INSTANCE_SAVE_24HR_THRESHOLD=1000
USE_WF_BINARY_LOAD=Y
EXTERNAL_FRONT_END_SERVER=
CLEAN_HOUR=0
CLEAN_TIMEOUT=240
CLEANUP_AGENT_SCHEDULER_TASKS=Y
CLEANUP_AGENT_RECORD_BATCH_SIZE=50000
CLEANUP_DAYS_TO_REVALIDATE_SYSTEM_OBJECTS=30
WF_MAX_BATCH_ENTRIES=200000
WF_AGENT_WAITTIME=100
WF_FUTURE_AGENT_SLEEPTIME=5
REPORTDATA_AGENT_SLEEPTIME=5
REPORTDATA_AGENT_RECORD_COUNT=500
DEFAULT_SYSTEM_USER_EMAIL_FOR_FORGOT_PASSWORD=
httpheader.Content-Security-Policy=frame-ancestors 'self' *.office.com *.office365.com *.cloud.microsoft;
httpheader.X-Frame-Options=SAMEORIGIN
httpheader.Strict-Transport-Security=max-age=63072000; includeSubDomains; preload
httpheader.X-Content-Type-Options=nosniff
httpheader.X-XSS-Protection=1; mode=block
httpheader.Cache-Control=no-cache, private
httpheader.Referrer-Policy=no-referrer
STATIC_CLIENT_RESOURCE_LIST=startsWith:/html/en/default/js/lib,endsWith:.css,endsWith:tririgastyle.jsp,endsWith:.js
STATIC_CLIENT_RESOURCE_CACHE_CONTROL_VALUE=private, max-age=604800
DEFAULT_TITLE=IBM Maximo Real Estate and Facilities
REPORT_MEMORY_USAGE_LIMIT=50
EXPORT_EXCEL_BATCH_PROCESS_SIZE=75000
RUNVALIDATOR=yes
Reserve=N
EXCHANGE_ROOT_PATH=exchange
EXTERNAL_MAIL_SERVER_USERNAME=
EXTERNAL_MAIL_SERVER_PASSWORD=
TRIRIGA_RESERVE_SUB_DOMAIN=
EXCHANGE_DOMAIN=
EXCHANGE_DOMAIN_MAX_LENGTH=255
EXCHANGE_GRAPH_EVENT_CONSOLIDATION_INTERVAL=
EXCHANGE_GRAPH_CALENDAR_EVENT_DEBOUNCE_INTERVAL=
TRIRIGA_RESERVE_OUTLOOK_TAB_LABEL=IBM TRIRIGA Reserve
CUSTOM_ERROR_PAGE=N
CUSTOM_ERROR_PAGE_PATH=
CSV_INJECTION_EXCLUDE_LIST=
TABLE_SIZE_CHECK_FOR_ORACLE=N
ErrorHandlerStrategy.MessageResetMinutes=60
SYSTEM_DEFAULT_TIMEZONE=UTC
PDF_EXPORT_GRAPHIC_STROKE_WIDTH_OVERRIDE=
BIRT_MEMORY_USAGE_LIMIT=35
ALLOWED_URL_FOR_REDIRECT=
ENABLE_UPLOAD_XSS_VALIDATION=N
ALLOW_PASSWORD_AUTO_COMPLETE=Y
SNMP_AGENT_PORT=161
SNMP_COMMUNICATION_PROTOCOL=UDP
UNSUCCESSFUL_LOGIN_ATTEMPT=10
VIRUS_SCAN_ENABLED=FALSE
VIRUS_SCANNER_IP_ADDRESS=
VIRUS_SCANNER_IP_PORT=
VIRUS_SCAN_SERVICE_NAME=
VIRUS_SCAN_ALLOW_204=
VIRUS_SCAN_FIRST_READ_TIMEOUT=
VIRUS_SCAN_SSL_ENABLED=FALSE
ALLOW_REVERSE_ASSOCIATION=FALSE
WEATHER_API_KEY=
ENABLE_CONCURRENT_AVAILABILITY=true
CONCURRENT_AVAILABILITY_POOL_SIZE=200
CONCURRENT_AVAILABILITY_REQUEST_BATCH_SIZE=10
PERFORMANCE_ANALYZER_MAX_FILE_SIZE_IN_MB=110
PERFORMANCE_LOGGING_THRESHOLD=100
SYNCHRONIZE_ACTIVATE_USER=Yes
ENHANCED_RECORD_RENDER_MODE=TRUE
IMAGE_URL=
REQUEST_RATE_LIMIT_ENABLED=false
REQUEST_RATE_LIMIT=200
REQUEST_RATE_LIMIT_REFILL_COUNT=100
REQUEST_RATE_LIMIT_REFILL_TIME_WINDOW=2
REQUEST_BUCKET_CLEANUP_INTERVAL=1
ENABLE_XSS_REGEX_VALIDATION=N
REVERSIBLE_ENCRYPTION_BATCH_SIZE=10000
FRONT_END_SERVER=example.ibm.com
COOKIE_SAME_SITE=Disabled