---
# Manage specific steps to configure Kafka Image Processor PVC for Civil component
# ------------------------------------------------------------------------
- name: "Debug Kafka Image Processor PVC configuration"
  debug:
    msg:
      - "Kafka Image Processor PVC Size ............ {{ manage_kafkaimageprocessor_pvc_size }}"
      - "Kafka Image Processor PVC Storage Class ... {{ manage_kafkaimageprocessor_pvc_storageclass }}"

- name: "Set Kafka Image Processor PVC configuration for civil component"
  set_fact:
    manage_civil_kafka_image_processor_pvc:
      kafkaImageProcessor:
        size: "{{ manage_kafkaimageprocessor_pvc_size }}"
        storageClassName: "{{ manage_kafkaimageprocessor_pvc_storageclass }}"

# Made with Bob
