---
# The following playbook is an attempt to automate the Cloud Pak for Data steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html

# 1. Base Setup and Verifications (Both OLM and Helm)
# -----------------------------------------------------------------------------
# Lookup default Cloud Pak for Data version based on MAS catalog
- include_tasks: "{{ role_path }}/../../common_tasks/determine-ibmcatalog-tag.yml"

- debug:
    msg:
      - "Catalog Version ............................ {{ (catalog_tag is defined and catalog_tag != '') | ternary(catalog_tag, 'Undefined') }}"
      - "Cloud Pak for Data version ................. {{ cpd_product_version | default('Undefined') }}"

- name: "Check that Cloud Pak for Data release version has been provided"
  assert:
    that:
      - cpd_product_version is defined and cpd_product_version != ""
    fail_msg: "Cloud Pak for Data version (cpd_product_version) is a required parameter to run this role"

- name: "Load supported Cloud Pak for Data information"
  include_vars: "{{ role_path }}/../../common_vars/cp4d_supported_versions.yml"

- name: "Check that provided Cloud Pak for Data version is supported for MAS"
  assert:
    that:
      - cpd_product_version in cpd_supported_versions
    fail_msg: "Cloud Pak for Data version ({{ cpd_product_version }}) is not a supported version for MAS. Supported Cloud Pak for Data versions for MAS are: {{ cpd_supported_versions }}"

# 2. Determine the Resolved Installation Method
# -----------------------------------------------------------------------------
- name: "Set resolved install method"
  set_fact:
    resolved_install_method: >-
      {%- if cpd_install_method == 'auto' -%}
        {%- if cpd_product_version is version('5.4.0', '>=') -%}
          helm
        {%- else -%}
          olm
        {%- endif -%}
      {%- else -%}
        {{ cpd_install_method }}
      {%- endif -%}

- name: "Check that an entitlement key has been provided"
  when: not skip_entitlement_key_flag
  assert:
    that: cpd_entitlement_key is defined and cpd_entitlement_key != ""
    fail_msg: "ibm_entitlement_key or cpd_entitlement_key override must be provided"

# 3. Create Required Namespaces
# -----------------------------------------------------------------------------
- name: "Create Cloud Pak for Data Namespaces"
  kubernetes.core.k8s:
    apply: yes
    template: "templates/cpd_platform/namespaces.yml.j2"

# 4. Install Entitlement Secrets
# -----------------------------------------------------------------------------
# Nothing in the cp4d base platform requires entitlement, but the services that we want to enable in CP4D do.
- name: "Install IBM Entitlement Key"
  when: not skip_entitlement_key_flag
  include_tasks: "tasks/entitlement.yml"

# We need to provide entitlement key for the wcs service accounts.
- include_tasks: "tasks/create-cpd-core-service-accounts.yml"

# 5. Route to Appropriate Platform Installation Path
# -----------------------------------------------------------------------------
- name: "Install Cloud Pak for Data Platform via OLM"
  when: resolved_install_method == 'olm'
  include_tasks: "olm/install-platform-olm.yml"

- name: "Install Cloud Pak for Data Platform via Helm"
  when: resolved_install_method == 'helm'
  include_tasks: "helm/install-platform-helm.yml"

# 6. Debug CPD Installation Details
# -----------------------------------------------------------------------------
- name: "Debug : Cloud Pak for Data {{ cpd_product_version }} details"
  debug:
    msg:
      - "CP4D Dashboard ......................... {{ cpd_admin_url }}"
      - "CP4D Admin Username .................... {{ cpd_admin_username }}"
      - "CP4D Admin Password .................... {{ cpd_admin_password_text }}"
