---
galaxy_info:
  author: Divyesh Khokhar (@Divyesh-K)
  description: Migrate AI Service from Open Data Hub (ODH) to Red Hat OpenShift AI (RHOAI)
  company: IBM
  license: EPL-2.0
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - ibm
    - mas
    - maximo
    - aiservice
    - odh
    - rhoai
    - migration

dependencies: []
