---
# Check if the namespace-scoped tenant operator is required.
# This role will set "is_migration_needed" and "requires_namespaced_tenant_operator"
# - include_role:
#     name: ibm.mas_devops.aiservice_migration
#   vars:
#     catalog_channel: "{{ aiservice_tenant_channel }}"
#     instance_id: "{{ aiservice_instance_id }}"
#     perform_check_only: true

# - include_tasks: tasks/namespace/main.yml

# # Create config for SLS
# - include_tasks: tasks/config_sls/main.yml

# # Create config for RSL
# - include_tasks: tasks/config_rsl/main.yml

# # Create config for DRO
# - include_tasks: tasks/config_dro/main.yml

# Load and validate scheduling configuration
- include_tasks: tasks/config_scheduling/main.yml

# create wx secret
# - include_tasks: tasks/watsonx/main.yml

# # Install the tenant operator
# - include_tasks: tasks/aiservice/main.yml
#   when:
#     - aiservice_channel is defined
#     - not aiservice_channel.startswith('9.1.')
#     - requires_namespaced_tenant_operator

# # create AI Broker tenant
# - include_tasks: tasks/tenant/main.yml
