galaxy_info:
  author: IBM
  description: Uninstall IBM Cloud Pak for Data and its services
  company: IBM

  license: EPL-2.0

  min_ansible_version: "2.10"

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - cp4d
    - cloudpak
    - devops
    - rhocp

dependencies:
  - role: ibm.mas_devops.ansible_version_check

# Made with Bob
