apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: {{oacle_db_instance_name}}
spec:
  sid: {{oacle_db_instance_name}}
  replicas: 1
  loadBalancer: true
  edition: enterprise
  adminPassword:
    secretName: oracle-admin
  charset: AL32UTF8
  pdbName: {{oacle_db_instance_name}}pdb1
  archiveLog: true
  initParams:
    pgaAggregateTarget: 512
    processes: 100
    sgaTarget: 1024
  image:
    pullFrom: container-registry.oracle.com/database/enterprise
    pullSecrets: oracle-registry
  persistence:
    accessMode: ReadWriteOnce
    size: {{oracle_db_size}}
    storageClass: ibmc-block-gold