---
- name: Check if SLS config file exists
  stat:
    path: "{{ mas_config_dir }}/sls.yml"
  register: sls_file_result

- name: Read SLS config from file
  vars:
    sls_file_cfg: "{{ lookup('file', '{{ mas_config_dir }}/sls.yml') | from_yaml_all }}"
  ansible.builtin.set_fact:
    slscfg:
      secret_name: "{{ sls_file_cfg[0].metadata.name }}"
      registration_key: "{{ sls_file_cfg[0].stringData.registrationKey }}"
      url: "{{ sls_file_cfg[1].spec.config.url }}"
      ca: "{{ sls_file_cfg[1].spec.certificates | map(attribute='crt') | join(',') | replace(',','\n') }}"
  when: sls_file_result.stat.exists

- name: Read SLS config from environment
  ansible.builtin.set_fact:
    slscfg:
      secret_name: "{{ lookup('env', 'AISERVICE_SLS_SECRET_NAME') }}"
      registration_key: "{{ lookup('env', 'AISERVICE_SLS_REGISTRATION_KEY') }}"
      url: "{{ lookup('env', 'AISERVICE_SLS_URL') }}"
      ca: "{{ lookup('env', 'AISERVICE_SLS_CA_CERT') | regex_replace('BEGIN CERTIFICATE', 'BEGIN_CERTIFICATE') | regex_replace('END CERTIFICATE', 'END_CERTIFICATE') | regex_replace('\\s+', '\n') | replace('BEGIN_CERTIFICATE', 'BEGIN CERTIFICATE')| replace('END_CERTIFICATE', 'END CERTIFICATE') }}"
  when: not sls_file_result.stat.exists

- name: "Validate SLS configuration"
  when: slscfg.secret_name | length == 0
  fail:
    msg: "slscfg.secret_name must not empty"

- name: "Validate SLS configuration"
  when: slscfg.registration_key | length == 0
  fail:
    msg: "slscfg.registration_key must not empty"

- name: "Validate SLS configuration"
  when: slscfg.url | length == 0
  fail:
    msg: "slscfg.url must not empty"

- name: "Validate SLS configuration"
  when: slscfg.ca | length == 0
  fail:
    msg: "slscfg.ca must not empty"

# BEGIN rollback
# The following steps will perform a roll back of the SLS secret namespace change performed when upgrading from 9.1 to 9.2.
# If the secret is detected in the tenant namespace then it is assumed that a rollback is necessary.
# Remove this block when 9.1 is no longer supported.
- name: Roll back SLS secret namespace change if necessary
  when:
    - aiservice_channel is defined
    - aiservice_channel.startswith('9.1.')
  block:
    - name: Check if SLS secret exists in tenant namespace
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        namespace: "{{ tenantNamespace }}"
        name: "{{ tenantNamespace }}----sls-secret"
      register: tenant_sls_secret_result
      no_log: true
    
    - name: Confirm if SLS secret rollback is needed
      set_fact:
        is_sls_secret_rollback_needed: {{ tenant_sls_secret_result.resources | length == 1 }}
    
    - name: "Move tenant SLS secret back to namespace {{ api_namespace }}"
      when: is_sls_secret_rollback_needed
      kubernetes.core.k8s:
        state: present
        namespace: "{{ api_namespace }}"
        definition: >
          {{ tenant_sls_secret_result.resources[0] | ibm.mas_devops.remove_dict_keys(['status', 'metadata.namespace', 'metadata.creationTimestamp',
          'metadata.generation', 'metadata.resourceVersion', 'metadata.uid', 'metadata.ownerReferences']) | to_yaml }}

    - name: "Delete tenant SLS secret from namespace {{ tenantNamespace }}"
      when: is_sls_secret_rollback_needed
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        namespace: "{{ tenantNamespace }}"
        name: "{{ tenantNamespace }}----sls-secret"
        kind: Secret

    - name: Confirm if rollback was performed
      ansible.builtin.debug:
        msg: "Was tenant SLS secret moved to namespace {{ api_namespace  }}? .......... {{ is_sls_secret_rollback_needed }}"

# END rollback

- name: Create SLS secret
  when: not is_sls_secret_rollback_needed
  kubernetes.core.k8s:
    state: present
    template: "templates/sls/sls-secret.yml.j2"
