galaxy_info:
  author: Lokesh Sreedhara
  description: Deploy Oracle instance configured for IBM Maximo Application Suite
  company: IBM

  license: UPL-1.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - oracle

dependencies: []