---
catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
catalog_channel: "{{ lookup('env', 'AISERVICE_CHANNEL') | default('', true) }}"
instance_id: "{{ lookup('env', 'AISERVICE_INSTANCE_ID') }}"
api_namespace: "aiservice-{{ aiservice_instance_id }}"
force_migration: "{{ lookup('env', 'AISERVICE_FORCE_MIGRATION') | default('False', True) | bool }}"
install_num_retries: "{{ lookup('env', 'AISERVICE_INSTALL_NUM_RETRIES') | default('60', True) | int }}"
install_wait_sec: "{{ lookup('env', 'AISERVICE_INSTALL_WAIT_SEC') | default('60', True) | int }}"

# When true, skips migration and only checks if a migration is needed
perform_check_only: "{{ lookup('env', 'AISERVICE_MIGRATION_PERFORM_CHECK_ONLY') | default('False', True) | bool }}"
